# Crear usuario en BD
POST http://localhost:8001/Registro
Content-Type: application/json

{
  "Nombres": "Maria",
  "Apellidos": "Perez",
  "contrasena": "Contraseña",
  "idFicha": 1
}
###

# Validar usuario y generar JWT
POST http://localhost:8001/login
Content-Type: application/json

{
  "Nombres": "Maria",
  "Apellidos": "Perez",
  "contrasena": "Contraseña"
}
###

# Consulta de aprendices
GET http://localhost:8001/Registro

###

# Consulta de programas
GET http://localhost:8001/programa

###

# Crear programa
POST http://localhost:8001/programa
Content-Type: application/json

{
  "nombrePrograma": "TICS"
}

###

# Actualizar programa
PUT http://localhost:8001/programa
Content-Type: application/json

{
  "idPrograma": 1,
  "nombrePrograma" : "ADSO"
}

###

# Eliminar programa
DELETE http://localhost:8001/programa
Content-Type: application/json

{
  "idPrograma": 2
}

###

# Consulta de asistencias
GET http://localhost:8001/asistencia

###

# Crear asistencia
POST http://localhost:8001/asistencia
Content-Type: application/json

{
  "idAprendiz": 7,
  "idHorario_Ficha_Asignatura": 1,
  "Fecha": "2026-07-31",
  "Estado": "Presente"
}
###

# Actualizar asistencia
PUT http://localhost:8001/asistencia
Content-Type: application/json

{
  "idAsistencia": 6,
  "idAprendiz": 7,
  "idHorario_Ficha_Asignatura": 1,
  "Fecha": "2026-07-31",
  "Estado": "Falta"
}
###

# Eliminar asistencia
DELETE http://localhost:8001/asistencia
Content-Type: application/json

{
  "idAsistencia": 6
}

###