# Crear usuario en BD
POST http://localhost:8001/Registro
Content-Type: application/json

{
  "Nombres": "Maria",
  "Apellidos": "Perez",
  "contrasena": "Contraseña",
  "idFicha": 1
}
###

# Validar usuario y generar JWT
POST http://localhost:8001/login
Content-Type: application/json

{
  "Nombres": "Maria",
  "Apellidos": "Perez",
  "contrasena": "Contraseña"
}
###

# Consulta de aprendices
GET http://localhost:8001/Registro
