# Crear usuario en BD
POST http://localhost:8001/Registro
Content-Type: application/json

{
  "Nombres": "Maria",
  "Apellidos": "Perez",
  "contrasena": "Contraseña",
  "idFicha": 1
}
###

# Validar usuario y generar JWT
POST http://localhost:8001/login
Content-Type: application/json

{
  "Nombres": "Juan Alejandro",
  "Apellidos": "Perez Salazar",
  "contrasena": "1234"
}
###

# Consulta de aprendices
GET http://localhost:8001/Registro

###

# Consultar aprendices
GET http://localhost:8001/Aprendiz

###

# Registrar aprendiz
POST http://localhost:8001/Aprendiz
Content-Type: application/json

{
    "Nombres": "Eduardo Alejandro",
    "Apellidos": "Hernandez Sandoval",
    "contrasena": "1234",
    "idFicha": 1
}

###

# Actualizar aprendiz
PUT http://localhost:8001/Aprendiz
Content-Type: application/json

{
    "idAprendiz": 1,
    "Nombres": "Juan Alejandro",
    "Apellidos": "Pérez Salazar",
    "contrasena": "1234",
    "idFicha": 1
}

###

# Eliminar aprendiz
DELETE http://localhost:8001/Aprendiz
Content-Type: application/json

{
    "idAprendiz": 2
}

###

# Consulta de programas
GET http://localhost:8001/programa

###

# Crear programa
POST http://localhost:8001/programa
Content-Type: application/json

{
  "nombrePrograma": "TICS"
}

###

# Actualizar programa
PUT http://localhost:8001/programa
Content-Type: application/json

{
  "idPrograma": 1,
  "nombrePrograma" : "ADSO"
}

###

# Eliminar programa
DELETE http://localhost:8001/programa
Content-Type: application/json

{
  "idPrograma": 3
}

###

# Consultar usuarios
GET http://localhost:8001/usuario

###

# Registrar usuario
POST http://localhost:8001/usuario
Content-Type: application/json

{
  "nombres": "Carlos Arturo",
  "apellidos": "Gomez",
  "contrasena": "1234",
  "idRol": 1
}

###

# Actualizar usuario
PUT http://localhost:8001/usuario
Content-Type: application/json

{
  "idUsuario": 1,
  "nombres": "Carlos Arturo",
  "apellidos": "Gomez Ramirez",
  "contrasena": "1234",
  "idRol": 1
}

###

### Eliminar usuario
DELETE http://localhost:8001/usuario
Content-Type: application/json

{
  "idUsuario": 2
}
# Consulta de asistencias
GET http://localhost:8001/asistencia

###

# Crear asistencia
POST http://localhost:8001/asistencia
Content-Type: application/json

{
  "idAprendiz": 7,
  "idHorario_Ficha_Asignatura": 1,
  "Fecha": "2026-07-31",
  "Estado": "Presente"
}
###

# Actualizar asistencia
PUT http://localhost:8001/asistencia
Content-Type: application/json

{
  "idAsistencia": 6,
  "idAprendiz": 7,
  "idHorario_Ficha_Asignatura": 1,
  "Fecha": "2026-07-31",
  "Estado": "Falta"
}
###

# Eliminar asistencia
DELETE http://localhost:8001/asistencia
Content-Type: application/json

{
  "idAsistencia": 6
}

###

# Consultar horarios
GET http://localhost:8001/horario

###

# Registrar horario
POST http://localhost:8001/horario
Content-Type: application/json

{
    "Dia": "Lunes",
    "HoraInicio": "08:00:00",
    "HoraFin": "10:00:00"
}

###

# Actualizar horario
PUT http://localhost:8001/horario
Content-Type: application/json

{
    "idHorario": 1,
    "Dia": "Martes",
    "HoraInicio": "08:00:00",
    "HoraFin": "10:00:00"
}

###

# Eliminar horario
DELETE http://localhost:8001/horario
Content-Type: application/json

{
    "idHorario": 1
}

###
